---
title: "The role of lithic bipolar technology in Western Iberia’s Upper Paleolithic: the case of Vale Boi (southern Portugal)"
author:
  - Pedro Horta (ICArEHB, University of Algarve, Faro, Portugal) pedroehorta@gmail.com
  - João Cascalheira (ICArEHB, University of Algarve, Faro, Portugal) jmcascalheira@ualg.pt
  - Nuno Bicho (ICArEHB, University of Algarve, Faro, Portugal) nbicho@ualg.pt
date: '`r Sys.Date()`'
output: 
    bookdown::word_document2: #subsistute by pdf_document2 or hmtl_document2 as necessary
      fig_caption: yes
      reference_docx: "../templates/template2.docx" 
bibliography: ScaledPiecesVB.bib
csl: "../templates/springer-humanities-author-date.csl"
abstract: |
  

---


```{r, setup, echo = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  warning = FALSE,
  message = FALSE,
  echo = FALSE,
  comment = "#>",
  dpi = 300,
  fig.width = 9,
  fig.path = "../figures/"
  )

#library(ScaledPiecesVB) # Or use devtools::load_all('.', quiet = T) if your code is in script files, rather than as functions in the `/R` diretory
```

```{r load_libraries, echo = FALSE}

library(dplyr)
library(FactoMineR)
library(factoextra)
library(ggpubr)
library(ggplot2)
library(ggrepel)

```

# Introduction



\newline

```{r }


```

\newline



# Materials and Methods





# Results


#Discussion


#Conclusion


#Acknowledgements



##### pagebreak


# References 
<div id="refs"></div>

##### pagebreak

### Colophon

This report was generated on `r Sys.time()` using the following computational environment and dependencies: 

```{r colophon, cache = FALSE}
# which R packages and versions?
devtools::session_info()
```

The current Git commit details are:

```{r}
# what commit is this file at? You may need to change the path value
# if your Rmd is not in analysis/paper/
git2r::repository("../..")
```
